name: smart_cafeteria
description: "Smart Cafeteria Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  change_case: ^2.1.0
  carousel_slider: ^4.2.1
  auto_size_text: ^3.0.0
  flutter_spinkit: ^5.2.1
  loading_animation_widget: ^1.2.1
  go_router: ^14.2.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.19.0
  get: ^4.6.6
  smooth_page_indicator: ^1.2.0
  readmore: ^3.0.0
  connectivity_plus: ^5.0.1

  # firebase
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  get_storage: ^2.1.1
  firebase_storage: ^12.1.1
  google_sign_in: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/app_logo.png"

flutter:
  uses-material-design: true
  assets:
     - assets/logos/
     - assets/categorical_image/
     - assets/test_image/
     - assets/test_icons/
     - assets/onboard_image/