 // File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1MR1oY-zpVJ7bw18uaKgZQAZRx0pTzE0',
    appId: '1:171370620446:android:99dd05f1d40a336e60f00f',
    messagingSenderId: '171370620446',
    projectId: 'smartcafe-202114064',
    storageBucket: 'smartcafe-202114064.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_eZ7GAP1ZMJiewKHPNW798TdT-pN434E',
    appId: '1:171370620446:ios:7255f8dd883e1e5760f00f',
    messagingSenderId: '171370620446',
    projectId: 'smartcafe-202114064',
    storageBucket: 'smartcafe-202114064.appspot.com',
    androidClientId: '171370620446-82r2snm8rruam7p270fn9l796pup89bc.apps.googleusercontent.com',
    iosClientId: '171370620446-g8hgtb68p79evic4ohjfmvu9lih5vhcp.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartCafeteria',
  );

}